
num_1=input("Plural Noun ")
num_2=input("Adjective ")
num_3=input("Adjective ")
num_4=input("Adjective ")
num_5=input("Adjective ")
num_6=input("Noun ")
num_7=input("Plural Noun ")
num_8=input("Adjective ")
num_9=input("Plural Noun ")
num_10=input("Adjective ")
print("Hello "+num_1+".\n I am "+num_2+" to see you all looking so "+num_3+". \n I hope you all had a "+num_4+" weekend.\n Today we will be starting with a "+num_5+" programming language.\n It is called "+num_6+". \n Now, I want you all to start by opening your "+num_7+" and looking at the "+num_8+" description for the project.\n Now, follow all the "+num_9+" and you will be on your way to creating a "+num_10+" project")